[package]
name = "flakeid"
version = "0.1.0"
authors = ["Anton Österberg <anton@42x.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.3"