name: Build & Test
on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
      - "src/**"
      - "tests/**"
      - "examples/**"
      - "build.rs"
      - ".github/workflows/rust.yml"
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
      max-parallel: 3
      fail-fast: false
    env:
      QUICKCHECK_TESTS: 1000000
    steps:
      - uses: actions/checkout@v1
      - name: Fetch Dependencies
        run: cargo fetch
      - name: Build
        run: cargo build --all-features
      - name: Run tests
        run: cargo test --all-features

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
      - name: rustfmt
        run: rustfmt --check src/*
